### ISSUE TITLE
Onboarding on Android tablets don't use the whole screen

### ISSUE THREAD

**Issue by pfmaggi** [microsoft/sketch360#11]
## Issue
The onboarding panel uses only half of the screen when running on a Tablet in landscape mode:

![device-2020-12-23-095246](https://user-images.githubusercontent.com/188886/102979118-e68bb280-4505-11eb-96d2-aaac8efdbc6c.png)

## Expected behavior
The onboarding should use the whole screen.  
There are probably few options to improve on the current implementation:
* use larger panels to use the whole screen
* center the panel on the screen
* show two panels, side by side

**Comment by mscherotter** [comment]
Which Tablet and OS version did you see this in?

**Comment by pfmaggi** [comment]
I've seen this behavior on a Samsung Tab S7 with Android 10.

**Comment by mscherotter** [comment]
This should now be fixed in the Google Play store.

**Comment by pfmaggi** [comment]
Thanks!  
It still looks a bit stretched but it is way better than before 😄 

![device-2021-02-26-142910](https://user-images.githubusercontent.com/188886/109306227-2ab96d00-783f-11eb-9e98-77824ccc7406.png)
