### ISSUE TITLE
Localize to German

### ISSUE THREAD

**Issue by mscherotter** [microsoft/sketch360#17]
- Localize [help file](https://github.com/microsoft/sketch360/blob/main/Source/about.DE.html)
- Localize Google Play Store description:

### Google Play Store
App name*
10 / 50 chars
This is how your app will appear on Google Play. It should be concise and not include price, rank, any emoji or repetitive symbols.
Sketch 360

Short description
77 / 80 chars
A short description for your app. Users can expand to view your full description.
Create 360-degree panoramic sketches that can easily be shared as 360 photos.

Full description*
1333 / 4000 chars
Sketch 360: A Microsoft Garage Project

Sketch 360 helps you easily create 360 degree panoramic sketches, which are useful when you want to create a quick sketch of a space, real or virtual, when modeling might take too long.

Whether you are an architect, a VR designer, an urban sketcher, a 3D game designer or a 360 video producer, you can easily construct an accurate sketch from a single viewpoint that's easily shareable online using Sketch 360.

Draw on one pane using equirectangular grid and stencils as guides. The stencils help you draw the vertical and curved horizontal lines that end up looking straight when seen in 360.

As you sketch on the drawing pane, the sketch is projected onto the inside of a sphere with you at the center, rotating the 360 view to point at the latest sketch stroke. You can also use the tilt and rotation of your device to determine the gaze of a virtual window pane.

Works great with multi-screen devices and devices that support pressure-sensitive pens like the Microsoft Surface Duo.

Export these images as viewable as 360 degree photos on sites like Facebook.com, Adobe Lightroom, Kuula.co or apps like VR Media Player.

Sketch 360 is a Microsoft Garage project. The Microsoft Garage turns fresh ideas into real projects. Learn more about The Garage at: http://microsoft.com/garage

**Comment by ferzkopp** [comment]
App name*
Sketch 360 

Short description
Erstellen Sie 360-Grad-Panoramaskizzen, die einfach als 360-Grad-Fotos geteilt werden können.

Full description*
Sketch 360: Ein Microsoft Garage Projekt

Sketch 360 hilft Ihnen, 360-Grad-Panoramaskizzen zu erstellen, die nützlich sind, wenn Sie eine schnelle Skizze eines realen oder virtuellen Raums erstellen möchten, und die manuelle Modellierung zu lange dauern würde.

Egal, ob Sie Architekt, VR-Designer, städtebaulicher Zeichner, 3D-Spieldesigner oder ein 360-Video-Produzent sind, können Sie mit Sketch 360 ganz einfach eine genaue Skizze aus einem einzigen Blickwinkel erstellen und leicht online gemeinsam nutzen.

Zeichnen Sie auf dem Bildschirm mit äquirektangularen Rastern und Schablonen als Hilfslinien. Diese Schablonen helfen Ihnen, die vertikalen und gekrümmten horizontalen Linien, welche am Ende im 360-Grad-Panorama gerade aussehen, präzise zu zeichnen.

Während Sie im Zeichnungsbereich skizzieren, wird die Skizze auf die Innenseite einer Kugel mit Ihnen in der Mitte projektiert, wobei sich die Drehung der 360-Ansicht automatisch auf den letzten Skizzenstrich anpasst. Sie können auch die Neigung und Drehung Ihres Geräts verwenden, um den Blick in die virtuellen 3D-Ansicht zu bestimmen.

Funktioniert hervorragend mit Geräten die mehreren Bildschirmen besitzen und druckempfindliche Stifte unterstützen, wie zum Beispiel das Microsoft Surface Duo.

Exportieren Sie diese Bilder als 360-Grad-Fotos auf Webseiten wie Facebook.com, Adobe Lightroom, Kuula.co oder Apps wie VR Media Player.

Sketch 360 ist ein Projekt der Microsoft Garage. Die Microsoft Garage verwandelt neue Ideen in realisierte Projekte. Erfahren Sie mehr über die Garage unter: http://microsoft.com/garage
