### ISSUE TITLE
Inking doesn't get erased on the screen

### ISSUE THREAD

**Issue by danielkornev** [microsoft/sketch360#25]
## Device Context
**Device:** Surface Duo
**Android:** 10
**Security Update:** April 2021
**MS Launcher:** Release version

## Details
While inking itself works for some reason erasing with Slim Surface Pen's Eraser doesn't. ```Strokes_Erased``` event is fired but inking remains visible on ```InkCanvasView```. I've tried to use ```InkCanvasView``` w/o specifying background, w/ "White" as background, and with "Transparent" background. In all 3 cases erasing event triggers but ink remains on the screen.

## Source Code (for repro)
https://github.com/danielkornev/XCourierApp

## Video
https://twitter.com/danielko/status/1389242598422978560

**Comment by danielkornev** [comment]
asking @mscherotter for help! )

**Comment by danielkornev** [comment]
:( 13 days passed (

**Comment by mscherotter** [comment]
Daniel, I'm sorry for the delay but I don't have a Surface Slim Pen to test with and the Surface pen eraser end works fine.  Have you tested with the Surface Pen?

**Comment by danielkornev** [comment]
Hi Michael!

Thanks a lot for answering me. Did you try my app?

Yes, I've tested with normal Surface Pen, and the issue remains.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mscherotter** [comment]
Are you invalidating the canvas?

**Comment by danielkornev** [comment]
Hmm, what is the correct way of doing this?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by danielkornev** [comment]
I've added this code:
![image](https://user-images.githubusercontent.com/5264043/119268758-0af6d280-bbfd-11eb-9e5e-8faf668128fd.png)

However, the only case when the canvas gets cleaned after "erasing ink" is when I change it from one-screen to two-screen. 

What am I doing wrong in here?

**Comment by mscherotter** [comment]
Do you have a simple test project that I can look at?
Michael

**Comment by danielkornev** [comment]
Sure: https://github.com/danielkornev/XCourierApp

It's a very simple project. All it has is two InkCanvasViews in one TwoPaneView.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by danielkornev** [comment]
BTW I've went through the call stack inside Xamarin.Forms.Inking, canvas invalidation is called during erasing event handling process.

But I still don't get what's wrong.

**Comment by danielkornev** [comment]
any updates? :)

**Comment by mscherotter** [comment]
No - I haven't had a chance to look at it yet.

**Comment by mscherotter** [comment]
Daniel,
I figured it out.  You need to paint the background in the InkCanvasView.Painting.

**MainPage.xaml**
<inking_views:InkCanvasView Margin="0,0" x:Name="LeftInkCanvasView" Painting="CanvasPainting"
											MinimumHeightRequest="1800" MinimumWidthRequest="2700" 
											HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" CanvasWidth="2700" CanvasHeight="1800" />

**MainPage.xaml.cs**
      private void CanvasPainting(object sender, SKCanvas e)
        {
			e.Clear(SKColors.WhiteSmoke);
        }

**Comment by danielkornev** [comment]
Indeed. That worked fine! Though if you use WhiteSmoke that Legal Pad's background is replaced by WhiteSmoke.

I've used Empty color and erasing works.

Thanks a lot!!!!!

**Comment by mscherotter** [comment]
The Painting event is the place to render the background if you are interested.
Michael

**Comment by danielkornev** [comment]
Oh, I've got that) but it wasn't obvious to me before your explanations. I've rarely written code with Xamarin Forms (but have long experience with WPF since its Avalon times).

Wonder if InkCanvasView will work with flipping page controls - but that's an another story.

Thank you very much for your time and help Michael!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by danielkornev** [comment]
btw this can be considered as closed
